const questions = [
    {
        qid: 1000,
        tid: 1000,
        type: 0,
        text: "How much is 2+2?",
        correct_answer: '4',
        incorrect_answer_1: "3",
        incorrect_answer_2: "5",
        incorrect_answer_3: "2020",
        uid: 'neuhold@gjh.sk',
    },
    {
        qid: 1001,
        tid: 1000,
        type: 0,
        text: "How much is 2*2?",
        correct_answer: '4',
        incorrect_answer_1: "3",
        incorrect_answer_2: "5",
        incorrect_answer_3: "6",
        uid: 'neuhold@gjh.sk',
    },
    {
        qid: 1002,
        tid: 1000,
        type: 0,
        text: "What shape is the Earth?",
        correct_answer: 'spherical',
        incorrect_answer_1: "plane",
        incorrect_answer_2: "cubic",
        incorrect_answer_3: "piramid",
        uid: 'neuhold@gjh.sk',
    },
    {
        qid: 1003,
        tid: 1000,
        type: 1,
        text: "What is Maiia's favourite color?",
        correct_answer: 'red',
        incorrect_answer_1: "",
        incorrect_answer_2: "",
        incorrect_answer_3: "",
        uid: 'neuhold@gjh.sk',
    },
    {
        qid: 1004,
        tid: 1001,
        type: 0,
        text: "How much is 3+2?",
        correct_answer: '5',
        incorrect_answer_1: "3",
        incorrect_answer_2: "4",
        incorrect_answer_3: "6",
        uid: 'neuhold@gjh.sk',
    },
    {
        qid: 1005,
        tid: 1001,
        type: 0,
        text: "How much is 10*10?",
        correct_answer: '1000',
        incorrect_answer_1: "1200",
        incorrect_answer_2: "1100",
        incorrect_answer_3: "900",
        uid: 'neuhold@gjh.sk',
    },
    {
        qid: 1006,
        tid: 1001,
        type: 0,
        text: "What shape is the Earth?",
        correct_answer: 'spherical',
        incorrect_answer_1: "plane",
        incorrect_answer_2: "cubic",
        incorrect_answer_3: "piramid",
        uid: 'neuhold@gjh.sk',
    },
    {
        qid: 1007,
        tid: 1001,
        type: 1,
        text: "What is Diana's favourite color?",
        correct_answer: 'pink',
        incorrect_answer_1: "",
        incorrect_answer_2: "",
        incorrect_answer_3: "",
        uid: 'neuhold@gjh.sk',
    },
    {
        qid: 1008,
        tid: 1002,
        type: 0,
        text: "How much is 10*10?",
        correct_answer: '1000',
        incorrect_answer_1: "1200",
        incorrect_answer_2: "1100",
        incorrect_answer_3: "900",
        uid: 'neuhold@gjh.sk',
    },
    {
        qid: 1009,
        tid: 1002,
        type: 0,
        text: "What shape is the Earth?",
        correct_answer: 'spherical',
        incorrect_answer_1: "plane",
        incorrect_answer_2: "cubic",
        incorrect_answer_3: "piramid",
        uid: 'neuhold@gjh.sk',
    },
    {
        qid: 1010,
        tid: 1002,
        type: 1,
        text: "What is Diana's favourite color?",
        correct_answer: 'pink',
        incorrect_answer_1: "",
        incorrect_answer_2: "",
        incorrect_answer_3: "",
        uid: 'neuhold@gjh.sk',
    }
  ];

export default questions;
  